<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.qualogy.com/internalgreeting/xsd"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:tns="urn:AbstractInternalGreetingService.wsdl"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ns1="urn:AbstractInternalGreetingService.wsdl/types">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/wsdl/InternalGreetingService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="GreetName" namespace="http://xmlns.qualogy.com/internalgreeting/xsd"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/wsdl/InternalGreetingService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Greeting" namespace="http://xmlns.qualogy.com/internalgreeting/xsd"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE DEC 23 10:46:28 CET 2014].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:variable name="hourOfDay" select="xp20:hours-from-dateTime (xp20:current-dateTime ( ) )"/>
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="$hourOfDay &lt; 12">
        <ns0:Greeting>
          <xsl:value-of select="concat (&quot;Good morning, &quot;, /ns0:GreetName, &quot; !&quot; )"/>
        </ns0:Greeting>
      </xsl:when>
      <xsl:when test="$hourOfDay &lt; 18">
        <ns0:Greeting>
          <xsl:value-of select="concat (&quot;Good afternoon, &quot;, /ns0:GreetName, &quot; !&quot; )"/>
        </ns0:Greeting>
      </xsl:when>
      <xsl:otherwise>
        <ns0:Greeting>
          <xsl:value-of select="concat (&quot;Good evening, &quot;, /ns0:GreetName, &quot; !&quot; )"/>
        </ns0:Greeting>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
</xsl:stylesheet>
