<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://qualogy.com/wsdl/greeting"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://qualogy.com/wsdl/greeting"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="SOAGreetingOrchestrator">
        <plnk:role name="GreetingPort" portType="tns:GreetingPort"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://qualogy.com/wsdl/greeting" location="oramds:/apps/wsdl/GreetingService.wsdl"/>
</wsdl:definitions>
